### ISSUE TITLE
Firefox (or other non-chromium-based browser) version

### ISSUE THREAD

**Issue by claustromaniac** [ayastreb/bandwidth-hero#3]
Are we allowed to even dream of one ever being developed? :pray:

**Comment by ayastreb** [comment]
I don't use Firefox and haven't developed any extensions for it, but it should be pretty similar to Chrome, I guess 😄
I'll try to look into it and see if I can port it to FF.

**Comment by ayastreb** [comment]
So the extension itself works ok in Firefox, but it turns out Firefox does not support WebP image format 😬 And at the moment proxy server converts everything to webp.
I'll have to change the proxy server to be able to serve compressed jpeg to Firefox, but data savings will be smaller in FF, since webp is ~30% lighter than jpeg.

**Comment by claustromaniac** [comment]
I read somewhere that the dev team was considering adding support for WebP eventually, but even if they don't, I'm sure many people would benefit from this. There are many data compression proxies around but most seem to have suspicious (if not outright ironic) privacy policies.

I must admit that I wasn't even expecting you to consider porting it, merely hoping, so you already deserve a medal in my books. :+1:

**Comment by ayastreb** [comment]
Ok, I've updated the proxy server and published the extension for Firefox - https://addons.mozilla.org/en-US/firefox/addon/bandwidth-hero/
Cheers!

**Comment by claustromaniac** [comment]
Amazing. Thank you so much!
